# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto 0
__all__ = ['Card']

# %% ../nbs/00_card.ipynb 8
class Card:
    "A playing card"
    def __init__(self, 
                 suit:int,  # An index into `suits`
                 rank:int): # An index into `ranks`
        self.suit = suit
        self.rank = rank
        
    def __str__(self):
        return f'{ranks[self.rank]} of {suits[self.suit]}'
    
    __repr__ = __str__
